use syntaxhrm_mysql;
select * from hs_hr_emp_dependents;
select emp_lastname from hs_hr_employees;
select job_title from ohrm_job_title ;
select employee_id,emp_firstname,emp_lastname from hs_hr_employees;
select * from ohrm_language;
select * from hs_hr_employees where employee_id=8335;
select distinct eec_relationship from hs_hr_emp_emergency_contacts;
select eexp_employer,eexp_jobtit from hs_hr_emp_work_experience where emp_number=9451;
select * from hs_hr_employees where emp_birthday>'1980-01-01';
select * from hs_hr_employees where job_title_code is null;
select emp_firstname, emp_lastname, emp_hm_telephone from hs_hr_employees where emp_hm_telephone is null order by emp_firstname;
select * from hs_hr_employees where emp_birthday is not null order by emp_lastname desc;
select * from hs_hr_employees where emp_lastname like '%a';
select * from ohrm_location where country_code not in ('us','ca','br');
select * from hs_hr_employees where emp_birthday>'1980-01-01' and emp_birthday<'2000-12-31';
select * from ohrm_nationality where name like 'c%';
select * from hs_hr_employees where emp_birthday= '____08__' order by emp_lastname; 
select * from ohrm_job_title where job_title='manager';
select emp_firstname,emp_lastname,emp_birthday from hs_hr_employees where job_title_code in (10,29);